const KEY='mpi_v5_data';const OLD_KEY='mpi_v4_data';let data=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem(OLD_KEY)||'null')||window.SEED_DATA;let festFilter='all',contactFilter='all',tableView=false;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const save=()=>{localStorage.setItem(KEY,JSON.stringify(data));window.cloudSync?.scheduleIran()};
function fmt(d){if(!d)return 'À vérifier';let x=new Date(d+'T12:00:00');return isNaN(x)?d:x.toLocaleDateString('fr-FR',{day:'numeric',month:'short',year:'numeric'})}
function dateKey(d){if(!d)return '';if(/^\d{4}-\d{2}-\d{2}$/.test(d))return d;let t=String(d).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace('1er','1');let mo={janvier:1,fevrier:2,mars:3,avril:4,mai:5,juin:6,juillet:7,aout:8,septembre:9,octobre:10,novembre:11,decembre:12};let m=t.match(/(\d{1,2})\s+(janvier|fevrier|mars|avril|mai|juin|juillet|aout|septembre|octobre|novembre|decembre)\s+(20\d{2})/);return m?`${m[3]}-${String(mo[m[2]]).padStart(2,'0')}-${String(m[1]).padStart(2,'0')}`:''}
function page(id){$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));let titles={dashboard:"Vue d’ensemble",festivals:"Festivals",calendar:"Calendrier",contacts:"Diffusion & contacts",communication:"Communication"};$('#pageTitle').textContent=titles[id];$('#addBtn').style.display=['festivals','contacts'].includes(id)?'block':'none';$('#addBtn').textContent=id==='festivals'?'+ Ajouter un festival':'+ Ajouter un contact';if(id==='calendar')renderCalendar()}
$$('nav button').forEach(b=>b.onclick=()=>page(b.dataset.page));$$('[data-goto]').forEach(b=>b.onclick=()=>page(b.dataset.goto));
function counts(){return {todo:data.festivals.filter(f=>f.status==='a_inscrire').length,sent:data.festivals.filter(f=>f.status==='inscrit').length,no:data.festivals.filter(f=>f.status==='refuse').length,iran:data.festivals.filter(f=>f.iranExil).length}}
function renderDash(){let c=counts();$('#stats').innerHTML=[['À inscrire',c.todo],['Inscrits',c.sent],['Refusés',c.no],['Iran / Exil',c.iran]].map(x=>`<div class=stat><strong>${x[1]}</strong><span>${x[0]}</span></div>`).join('');
let today=new Date().toISOString().slice(0,10);let todo=data.festivals.filter(f=>f.status==='a_inscrire'&&dateKey(f.deadline)&&dateKey(f.deadline)>=today).sort((a,b)=>dateKey(a.deadline).localeCompare(dateKey(b.deadline))).slice(0,6);$('#nextDeadlines').innerHTML=todo.map(f=>`<div class=minirow><div><b>${f.name}</b><br><small>${f.city||''} ${f.iranExil?'· Iran / Exil':''}</small></div><span class=datechip>${fmt(f.deadline)}</span></div>`).join('')||'<p class=hint>Aucune deadline renseignée.</p>';
let sent=data.festivals.filter(f=>f.status==='inscrit').map(f=>({...f,calcResponse:f.response||approxResponse(f)})).filter(f=>f.calcResponse).sort((a,b)=>a.calcResponse.localeCompare(b.calcResponse)).slice(0,6);$('#nextResponses').innerHTML=sent.map(f=>`<div class=minirow><div><b>${f.name}</b><br><small>${f.response?'Date renseignée':'Date estimée'}</small></div><span class="datechip orangechip">${fmt(f.calcResponse)}</span></div>`).join('')||'<p class=hint>Aucune réponse datée.</p>'}
function approxResponse(f){if(!f.festivalStart)return '';let d=new Date(f.festivalStart+'T12:00:00');d.setDate(d.getDate()-45);return d.toISOString().slice(0,10)}
function statusLabel(s){return s==='inscrit'?'Inscrit':s==='refuse'?'Refusé':'À inscrire'}
function filteredFest(){let q=$('#festivalSearch').value.toLowerCase();let a=data.festivals.filter(f=>(festFilter==='all'||(festFilter==='iran'?f.iranExil:f.status===festFilter))&&JSON.stringify(f).toLowerCase().includes(q));let sort=$('#sortFestival').value;if(sort==='deadline')a.sort((x,y)=>(dateKey(x.deadline)||'9999').localeCompare(dateKey(y.deadline)||'9999'));if(sort==='name')a.sort((x,y)=>x.name.localeCompare(y.name));if(sort==='status')a.sort((x,y)=>x.status.localeCompare(y.status));return a}
function renderFest(){let a=filteredFest();$('#festivalCards').innerHTML=a.map(f=>`<article class="card ${f.status}"><div style="display:flex;justify-content:space-between">${f.iranExil?'<span class=badge>Iran / Exil</span>':'<span></span>'}<span class="status ${f.status}">${statusLabel(f.status)}</span></div><h3>${esc(f.name)}</h3><div class=meta>${esc(f.city||'Ville à vérifier')}${f.country?' · '+esc(f.country):''}<br>${esc(f.dates||'Dates à vérifier')}</div><div class=facts><div class=fact><small>Deadline</small><b>${fmt(f.deadline)}</b></div><div class=fact><small>Prix</small><b>${esc(f.price||'Prix à vérifier')}</b></div><div class=fact><small>Durée acceptée</small><b>${esc(f.duration||'À vérifier')}</b></div><div class=fact><small>Réponse</small><b>${fmt(f.response||approxResponse(f))}</b></div></div><div class=actions>${f.url?`<a href="${esc(f.url)}" target=_blank>Site ↗</a>`:''}<button onclick="editFestival('${f.id}')">Modifier</button><button class=danger onclick="delFestival('${f.id}')">Supprimer</button></div></article>`).join('');
$('#festivalTable').innerHTML=`<table><thead><tr><th>Festival</th><th>Statut</th><th>Iran/Exil</th><th>Ville</th><th>Pays</th><th>Deadline</th><th>Prix</th><th>Durée</th><th></th></tr></thead><tbody>${a.map(f=>`<tr><td><b>${esc(f.name)}</b></td><td>${statusLabel(f.status)}</td><td>${f.iranExil?'Oui':''}</td><td>${esc(f.city)}</td><td>${esc(f.country)}</td><td>${fmt(f.deadline)}</td><td>${esc(f.price)}</td><td>${esc(f.duration)}</td><td><button onclick="editFestival('${f.id}')">Modifier</button></td></tr>`).join('')}</tbody></table>`}
$('#festivalSearch').oninput=renderFest;$('#sortFestival').onchange=renderFest;$$('#statusTabs button').forEach(b=>b.onclick=()=>{$$('#statusTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');festFilter=b.dataset.filter;renderFest()});$('#viewToggle').onclick=()=>{tableView=!tableView;$('#festivalCards').classList.toggle('hidden',tableView);$('#festivalTable').classList.toggle('hidden',!tableView);$('#viewToggle').textContent=tableView?'▦ Cartes':'☷ Tableau'};
function renderContacts(){let q=$('#contactSearch').value.toLowerCase();let a=data.contacts.filter(c=>(contactFilter==='all'||c.type===contactFilter)&&JSON.stringify(c).toLowerCase().includes(q));$('#contactCards').innerHTML=a.map(c=>{let d=c.data||{};return `<article class=contact><div style="display:flex;justify-content:space-between"><span class=type>${c.type}</span>${c.iran?'<span class="badge iranbadge">Iran</span>':''}</div><h3>${esc(c.name)}</h3><p>${esc(d['Activité / ligne éditoriale']||d['Intérêt pour le film (appréciation)']||'')}</p><div class=meta>${esc(d.Pays||'')} ${d.Ville?'· '+esc(d.Ville):''}</div><div class=actions style="margin-top:12px">${d.Site?`<a href="${esc(d.Site)}" target=_blank>Site ↗</a>`:''}<button onclick="editContact('${c.id}')">Modifier</button><button class=danger onclick="delContact('${c.id}')">Supprimer</button></div></article>`}).join('')}
$('#contactSearch').oninput=renderContacts;$$('#contactTabs button').forEach(b=>b.onclick=()=>{$$('#contactTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');contactFilter=b.dataset.type;renderContacts()});
let calDate=new Date(),calView='month';
function calendarEvents(){let mode=$('#calendarRange').value,ev=[];data.festivals.forEach(f=>{if(f.status==='a_inscrire'&&dateKey(f.deadline)&&(mode==='all'||mode==='todo'))ev.push({id:f.id,date:dateKey(f.deadline),type:'todo',name:f.name,label:"Date limite d'inscription"});if(f.status==='inscrit'&&dateKey(f.response||approxResponse(f))&&(mode==='all'||mode==='response'))ev.push({id:f.id,date:dateKey(f.response||approxResponse(f)),type:'response',name:f.name,label:f.response?'Réponse attendue':'Réponse estimée (J-45)'});if(f.festivalStart&&dateKey(f.festivalStart)&&mode==='all')ev.push({id:f.id,date:dateKey(f.festivalStart),type:'festival',name:f.name,label:'Début du festival'})});return ev.sort((a,b)=>a.date.localeCompare(b.date))}
function renderCalendar(){let ev=calendarEvents();$('#calendarList').innerHTML=ev.map(e=>`<div class="event ${e.type}" onclick="editFestival('${e.id}')" title="Ouvrir la fiche festival"><b>${fmt(e.date)}</b><i class=ball></i><div><b>${esc(e.name)}</b><br><small>${e.label}</small></div><span>${e.type==='todo'?'Inscription':e.type==='response'?'Réponse':'Festival'}</span></div>`).join('')||'<p class=hint>Aucune échéance.</p>';let y=calDate.getFullYear(),m=calDate.getMonth(),first=new Date(y,m,1),offset=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate(),prevDays=new Date(y,m,0).getDate();$('#calLabel').textContent=first.toLocaleDateString('fr-FR',{month:'long',year:'numeric'});let cells=['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'].map(x=>`<div class=dayhead>${x}</div>`);for(let i=0;i<42;i++){let day=i-offset+1,dt,muted=false;if(day<1){dt=new Date(y,m-1,prevDays+day);muted=true}else if(day>days){dt=new Date(y,m+1,day-days);muted=true}else dt=new Date(y,m,day);let key=dt.getFullYear()+'-'+String(dt.getMonth()+1).padStart(2,'0')+'-'+String(dt.getDate()).padStart(2,'0'),items=ev.filter(e=>e.date===key);cells.push(`<div class="daycell ${muted?'muted':''}"><span>${dt.getDate()}</span>${items.slice(0,3).map(e=>`<div class="calevent ${e.type}" onclick="event.stopPropagation();editFestival('${e.id}')" title="Ouvrir la fiche">${esc(e.name)}</div>`).join('')}${items.length>3?`<small>+${items.length-3}</small>`:''}</div>`)}$('#calendarMonth').innerHTML=cells.join('')}
$('#calendarRange').onchange=renderCalendar;
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function openModal(title,html){$('#modalTitle').textContent=title;$('#editForm').innerHTML=html;$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}
function festivalForm(f={}){return `<div class=formgrid><div class="field wide"><label>Nom</label><input name=name required value="${esc(f.name||'')}"></div><div class=field><label>Statut</label><select name=status><option value=a_inscrire ${f.status==='a_inscrire'?'selected':''}>À inscrire</option><option value=inscrit ${f.status==='inscrit'?'selected':''}>Inscrit</option><option value=refuse ${f.status==='refuse'?'selected':''}>Refusé</option></select></div><div class=field><label>Iran / Exil</label><select name=iranExil><option value=false>Non</option><option value=true ${f.iranExil?'selected':''}>Oui</option></select></div><div class=field><label>Dates du festival</label><input name=dates value="${esc(f.dates||'')}"></div><div class=field><label>Début du festival</label><input type=date name=festivalStart value="${f.festivalStart||''}"></div><div class=field><label>Pays</label><input name=country value="${esc(f.country||'')}"></div><div class=field><label>Ville</label><input name=city value="${esc(f.city||'')}"></div><div class=field><label>Deadline</label><input type=date name=deadline value="${f.deadline||''}"></div><div class=field><label>Réponse envisagée</label><input type=date name=response value="${f.response||''}"></div><div class=field><label>Prix</label><input name=price value="${esc(f.price||'Prix à vérifier')}"></div><div class=field><label>Durée max / section</label><input name=duration value="${esc(f.duration||'À vérifier')}"></div><div class="field wide"><label>Site web</label><input name=url value="${esc(f.url||'')}"></div><div class=field><label>Film produit après</label><input name=producedAfter value="${esc(f.producedAfter||'')}"></div><div class=field><label>Durée minimum</label><input name=minDuration value="${esc(f.minDuration||'')}"></div><div class=field><label>Pays de production admis</label><input name=eligibleCountries value="${esc(f.eligibleCountries||'')}"></div><div class=field><label>Format de projection</label><input name=projectionFormat value="${esc(f.projectionFormat||'')}"></div><div class=field><label>Sous-titrage requis</label><input name=subtitleRequirement value="${esc(f.subtitleRequirement||'')}"></div><div class=field><label>Première / exclusivité</label><input name=premiereRequirement value="${esc(f.premiereRequirement||'')}"></div><div class="field wide"><label>Conditions d’éligibilité</label><textarea name=eligibility>${esc(f.eligibility||'')}</textarea></div><div class="field wide"><label>Notes</label><textarea name=notes>${esc(f.notes||'')}</textarea></div></div><button class=primary type=submit>Enregistrer</button>`}
function editFestival(id){let f=data.festivals.find(x=>x.id===id);openModal(f?'Modifier le festival':'Ajouter un festival',festivalForm(f||{}));$('#editForm').onsubmit=e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));o.iranExil=o.iranExil==='true';if(f)Object.assign(f,o);else data.festivals.push({...o,id:'new-'+Date.now()});save();closeModal();renderAll()}}
function delFestival(id){if(confirm('Supprimer ce festival ?')){data.festivals=data.festivals.filter(x=>x.id!==id);save();renderAll()}}
function editContact(id){let c=data.contacts.find(x=>x.id===id);let d=c?.data||{};openModal(c?'Modifier le contact':'Ajouter un contact',`<div class=formgrid><div class="field wide"><label>Nom</label><input name=name required value="${esc(c?.name||'')}"></div><div class=field><label>Type</label><select name=type>${['Vendeur','Diffuseur','Plateforme','Association','Distributeur'].map(x=>`<option ${c?.type===x?'selected':''}>${x}</option>`).join('')}</select></div><div class=field><label>Pays</label><input name=Pays value="${esc(d.Pays||'')}"></div><div class=field><label>Ville</label><input name=Ville value="${esc(d.Ville||'')}"></div><div class="field wide"><label>Activité / ligne éditoriale</label><textarea name=activity>${esc(d['Activité / ligne éditoriale']||'')}</textarea></div><div class="field wide"><label>Site</label><input name=Site value="${esc(d.Site||'')}"></div><div class="field wide"><label>Notes / suivi</label><textarea name=notes>${esc(d['Réponse / remarques de suivi']||'')}</textarea></div></div><button class=primary>Enregistrer</button>`);$('#editForm').onsubmit=e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target)),obj={id:c?.id||'contact-'+Date.now(),name:o.name,type:o.type,data:{...(c?.data||{}),Pays:o.Pays,Ville:o.Ville,Site:o.Site,'Activité / ligne éditoriale':o.activity,'Réponse / remarques de suivi':o.notes}};if(c)Object.assign(c,obj);else data.contacts.push(obj);save();closeModal();renderAll()}}
function delContact(id){if(confirm('Supprimer ce contact ?')){data.contacts=data.contacts.filter(x=>x.id!==id);save();renderAll()}}
$('#addBtn').onclick=()=>$('.page.active').id==='festivals'?editFestival():editContact();
let assets=JSON.parse(localStorage.getItem('mpi_assets')||'[]');function renderAssets(){$('#assets').innerHTML=assets.map((a,i)=>`<div class=asset><b>${esc(a.label)}</b><br><a href="${esc(a.url)}" target=_blank>${esc(a.url)}</a> <button onclick="assets.splice(${i},1);saveAssets()">×</button></div>`).join('')||'<p class=hint>Aucun lien ajouté.</p>'}function addAsset(){let label=prompt('Nom (ex. Bande-annonce, Dossier de presse)');if(!label)return;let url=prompt('Lien');if(url){assets.push({label,url});saveAssets()}}function saveAssets(){localStorage.setItem('mpi_assets',JSON.stringify(assets));window.cloudSync?.scheduleIran();renderAssets()}
function renderAll(){renderDash();renderFest();renderContacts();renderCalendar();renderAssets()}renderAll();
$('#calMonthBtn').onclick=()=>{calView='month';$('#calendarMonth').classList.remove('hidden');$('#calendarList').classList.add('hidden');$('#calMonthBtn').classList.add('active');$('#calListBtn').classList.remove('active')};$('#calListBtn').onclick=()=>{calView='list';$('#calendarMonth').classList.add('hidden');$('#calendarList').classList.remove('hidden');$('#calListBtn').classList.add('active');$('#calMonthBtn').classList.remove('active')};$('#calPrev').onclick=()=>{calDate.setMonth(calDate.getMonth()-1);renderCalendar()};$('#calNext').onclick=()=>{calDate.setMonth(calDate.getMonth()+1);renderCalendar()};$('#calToday').onclick=()=>{calDate=new Date();renderCalendar()};

// ---- V4: contacts CRM + film master sheet + assisted imports ----
const FILM_KEY='mpi_v4_film';
function normalizeContacts(){
 data.contacts.forEach(c=>{c.data=c.data||{}; let d=c.data;
   if(d['Uniquement Iran ?']==='Oui') c.iran=true;
   c.country=c.country||d.Pays||''; c.city=c.city||d.Ville||'';
   c.email=c.email||d.Email||''; c.phone=c.phone||d.Téléphone||'';
   c.contactName=c.contactName||d['Nom du contact']||'';
   c.contactDate=c.contactDate||dateish(d['Date de contact']);
   c.followupDate=c.followupDate||dateish(d['Date de relance']);
   c.crmStatus=c.crmStatus||((c.contactDate)?'contacte':'a_contacter');
   c.reply=c.reply||'pas_de_reponse';
 })}
function dateish(v){if(!v)return '';let s=String(v);if(/^\d{4}-\d\d-\d\d/.test(s))return s.slice(0,10);return ''}
normalizeContacts();save();

function contactStatusLabel(s){return ({a_contacter:'À contacter',contacte:'Contacté',a_relancer:'À relancer',reponse:'Réponse reçue'})[s]||'À contacter'}
function replyLabel(s){return ({pas_de_reponse:'Pas de réponse',positif:'Positif',negatif:'Négatif',discussion:'En discussion'})[s]||'Pas de réponse'}
function needsFollowup(c){if(!c.contactDate||c.crmStatus==='reponse')return false;let d=new Date(c.followupDate||c.contactDate);return (Date.now()-d.getTime())/86400000>=14}
let contactCountry='all',contactCrm='all',contactIran=false,contactSort='name';

const oldRenderContacts=renderContacts;
renderContacts=function(){
 let q=$('#contactSearch').value.toLowerCase();
 let a=data.contacts.filter(c=>(contactFilter==='all'||c.type===contactFilter)&&(!contactIran||c.iran)&&(contactCountry==='all'||c.country===contactCountry)&&(contactCrm==='all'||c.crmStatus===contactCrm)&&JSON.stringify(c).toLowerCase().includes(q));
 a.sort((x,y)=>contactSort==='country'?(x.country||'').localeCompare(y.country||''):contactSort==='date'?(y.contactDate||'').localeCompare(x.contactDate||''):(x.name||'').localeCompare(y.name||''));
 $('#contactCards').innerHTML=a.map(c=>`<article class=contact><div class=contacttop><span class=type>${c.type}</span>${c.iran?'<span class="badge iran">Iran</span>':''}</div><h3>${esc(c.name)}</h3><div class=meta>${esc(c.country)} ${c.city?'· '+esc(c.city):''}</div><div class="crmline"><span class="crm ${c.crmStatus}">${contactStatusLabel(c.crmStatus)}</span>${needsFollowup(c)?'<span class="crm warn">Relance +14j</span>':''}</div><p>${esc(c.data?.['Activité / ligne éditoriale']||'')}</p><div class=contactdetails>${c.contactName?`<span>👤 ${esc(c.contactName)}</span>`:''}${c.email?`<span>✉ ${esc(c.email)}</span>`:''}${c.phone?`<span>☎ ${esc(c.phone)}</span>`:''}${c.contactDate?`<span>Contact : ${fmt(c.contactDate)}</span>`:''}${c.reply!=='pas_de_reponse'?`<span>Retour : ${replyLabel(c.reply)}</span>`:''}</div><div class=actions style="margin-top:12px">${c.data?.Site?`<a href="${esc(c.data.Site)}" target=_blank>Site ↗</a>`:''}<button onclick="editContactV4('${c.id}')">Modifier</button><button class=danger onclick="delContact('${c.id}')">Supprimer</button></div></article>`).join('')||'<div class=empty>Aucun contact avec ces filtres.</div>';
}
function setupContactFilters(){
 let tb=$('#contacts .toolbar'); if(!tb||$('#crmFilters'))return;
 let countries=[...new Set(data.contacts.map(c=>c.country).filter(Boolean))].sort();
 let wrap=document.createElement('div');wrap.id='crmFilters';wrap.className='filterrow';wrap.innerHTML=`<button id=iranOnly>Iran uniquement</button><select id=countryFilter><option value=all>Tous les pays</option>${countries.map(x=>`<option>${esc(x)}</option>`).join('')}</select><select id=crmFilter><option value=all>Tous les suivis</option><option value=a_contacter>À contacter</option><option value=contacte>Contactés</option><option value=a_relancer>À relancer</option><option value=reponse>Réponse reçue</option></select><select id=contactSort><option value=name>Trier : nom</option><option value=country>Trier : pays</option><option value=date>Trier : date de contact</option></select>`;
 tb.after(wrap);
 $('#iranOnly').onclick=()=>{contactIran=!contactIran;$('#iranOnly').classList.toggle('active',contactIran);renderContacts()};
 $('#countryFilter').onchange=e=>{contactCountry=e.target.value;renderContacts()};
 $('#crmFilter').onchange=e=>{contactCrm=e.target.value;renderContacts()};
 $('#contactSort').onchange=e=>{contactSort=e.target.value;renderContacts()};
}
function editContactV4(id){
 let c=data.contacts.find(x=>x.id===id),d=c?.data||{};
 openModal(c?'Modifier le contact':'Ajouter un contact',`<div class=formgrid><div class="field wide"><label>Organisme</label><input name=name required value="${esc(c?.name||'')}"></div><div class=field><label>Type</label><select name=type>${['Vendeur','Diffuseur','Plateforme','Association','Distributeur'].map(x=>`<option ${c?.type===x?'selected':''}>${x}</option>`).join('')}</select></div><div class=field><label>Spécifique Iran ?</label><select name=iran><option value=false>Non</option><option value=true ${c?.iran?'selected':''}>Oui</option></select></div><div class=field><label>Pays</label><input name=country value="${esc(c?.country||'')}"></div><div class=field><label>Ville</label><input name=city value="${esc(c?.city||'')}"></div><div class=field><label>Nom du contact</label><input name=contactName value="${esc(c?.contactName||'')}"></div><div class=field><label>Email</label><input type=email name=email value="${esc(c?.email||'')}"></div><div class=field><label>Téléphone</label><input name=phone value="${esc(c?.phone||'')}"></div><div class=field><label>Site</label><input name=Site value="${esc(d.Site||'')}"></div><div class=field><label>Date de contact</label><input type=date name=contactDate value="${c?.contactDate||''}"></div><div class=field><label>Date de relance</label><input type=date name=followupDate value="${c?.followupDate||''}"></div><div class=field><label>État</label><select name=crmStatus>${[['a_contacter','À contacter'],['contacte','Contacté'],['a_relancer','À relancer'],['reponse','Réponse reçue']].map(x=>`<option value=${x[0]} ${c?.crmStatus===x[0]?'selected':''}>${x[1]}</option>`).join('')}</select></div><div class=field><label>Retour</label><select name=reply>${[['pas_de_reponse','Pas de réponse'],['positif','Positif'],['negatif','Négatif'],['discussion','En discussion']].map(x=>`<option value=${x[0]} ${c?.reply===x[0]?'selected':''}>${x[1]}</option>`).join('')}</select></div><div class="field wide"><label>Activité / ligne éditoriale</label><textarea name=activity>${esc(d['Activité / ligne éditoriale']||'')}</textarea></div><div class="field wide"><label>Notes / historique</label><textarea name=notes>${esc(d['Réponse / remarques de suivi']||'')}</textarea></div></div><button class=primary>Enregistrer</button>`);
 $('#editForm').onsubmit=e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));let obj={id:c?.id||'contact-'+Date.now(),name:o.name,type:o.type,iran:o.iran==='true',country:o.country,city:o.city,contactName:o.contactName,email:o.email,phone:o.phone,contactDate:o.contactDate,followupDate:o.followupDate,crmStatus:o.crmStatus,reply:o.reply,data:{...(c?.data||{}),Pays:o.country,Ville:o.city,Site:o.Site,'Uniquement Iran ?':o.iran==='true'?'Oui':'Non','Activité / ligne éditoriale':o.activity,'Réponse / remarques de suivi':o.notes}};if(c)Object.assign(c,obj);else data.contacts.push(obj);save();closeModal();setupContactFilters();renderAll()}
}
editContact=editContactV4;

function loadFilm(){
 let film=JSON.parse(localStorage.getItem(FILM_KEY)||'{}');let form=$('#filmForm');if(!form)return;
 Object.entries(film).forEach(([k,v])=>{let el=form.elements[k];if(el)el.value=v});
 updateFilmProgress();
}
function saveFilm(){let o=Object.fromEntries(new FormData($('#filmForm')));localStorage.setItem(FILM_KEY,JSON.stringify(o));window.cloudSync?.scheduleIran();updateFilmProgress();alert('Fiche du film enregistrée.')}
function updateFilmProgress(){let form=$('#filmForm');if(!form)return;let required=['title','internationalTitle','year','productionCountry','duration','languages','subtitles','logline','shortSynopsis','longSynopsis','director','production','producer','directorBio','directorStatement','email','screeningUrl','trailer','poster','presskit'];let filled=required.filter(k=>String(form.elements[k]?.value||'').trim()).length;let missing=required.filter(k=>!String(form.elements[k]?.value||'').trim()).map(k=>form.elements[k]?.previousElementSibling?.textContent||k);let pct=Math.round(filled/required.length*100);$('#filmProgress').innerHTML=`<div class=readiness><div><b>Dossier prêt : ${filled}/${required.length}</b><span>${pct}% des informations essentielles</span></div><div class=progress><i style="width:${pct}%"></i></div>${missing.length?`<details><summary>${missing.length} information(s) à compléter</summary><p>${missing.map(esc).join(' · ')}</p></details>`:'<strong>✓ Informations essentielles complètes</strong>'}</div>`}
$('#saveFilmBtn')?.addEventListener('click',saveFilm);$('#filmForm')?.addEventListener('input',updateFilmProgress);
$('#filmImportBtn')?.addEventListener('click',()=>openImport('film'));
function openImport(kind){
 let isFilm=kind==='film';openModal(isFilm?'Importer la fiche du film':'Importer un festival',`<div class=importbox><p><b>${isFilm?'FilmFreeway':'FilmFreeway ou Docfilmdepot'}</b></p><p>Colle l’adresse de la fiche. Dans cette V4 locale, l’outil prépare l’import et conserve l’URL, mais la lecture automatique complète d’un site externe nécessitera la version hébergée (les navigateurs bloquent souvent ces lectures directes).</p><div class=field><label>URL</label><input name=importUrl type=url required placeholder="${isFilm?'https://filmfreeway.com/...':'https://filmfreeway.com/... ou https://docfilmdepot.com/...'}"></div><div class=importnote>Après migration en ligne : URL → préremplissage → écran de vérification → validation. La saisie manuelle reste toujours disponible.</div><button class=primary>Continuer</button></div>`);
 $('#editForm').onsubmit=e=>{e.preventDefault();let url=new FormData(e.target).get('importUrl');closeModal();if(isFilm){let film=JSON.parse(localStorage.getItem(FILM_KEY)||'{}');film.sourceUrl=url;localStorage.setItem(FILM_KEY,JSON.stringify(film));window.cloudSync?.scheduleIran();alert('Lien FilmFreeway enregistré. Le préremplissage automatique sera activé avec la version hébergée.')}else{editFestival();setTimeout(()=>{let el=$('#editForm [name=url]');if(el)el.value=url},0)}}
}
$('#importFestivalBtn')?.addEventListener('click',()=>openImport('festival'));
const oldPage=page;page=function(id){oldPage(id);$('#importFestivalBtn')?.classList.toggle('hidden',id!=='festivals');if(id==='contacts'){setupContactFilters();renderContacts()}if(id==='communication')loadFilm()}
setupContactFilters();loadFilm();renderContacts();

// ---- V5: submission checklist + practical festival import ----
const checklistItems=[
 ['title','Titre original'],['internationalTitle','Titre international'],['duration','Durée'],['year','Année'],
 ['productionCountry','Pays de production'],['languages','Langue(s)'],['subtitles','Sous-titres'],
 ['shortSynopsis','Synopsis court'],['longSynopsis','Synopsis long'],['director','Réalisation'],
 ['directorBio','Bio réalisation'],['directorStatement',"Note d'intention"],['producer','Production / producteur'],
 ['screeningUrl','Lien de visionnage'],['trailer','Bande-annonce'],['poster','Affiche'],
 ['stills','Photos / stills'],['directorHeadshot','Portrait réalisation'],['presskit','Dossier de presse'],
 ['submitterEmail','Email déposant'],['pastScreenings','Projections antérieures'],['rightsInfo','Droits musique / archives']
];
function renderSubmissionChecklist(){let f=$('#filmForm'),box=$('#submissionChecklist');if(!f||!box)return;box.innerHTML=checklistItems.map(([k,l])=>{let ok=!!String(f.elements[k]?.value||'').trim();return `<div class="check ${ok?'done':''}"><i>${ok?'✓':'○'}</i><span>${esc(l)}</span></div>`}).join('')}
$('#filmForm')?.addEventListener('input',renderSubmissionChecklist);renderSubmissionChecklist();
const _loadFilm=loadFilm;loadFilm=function(){_loadFilm();renderSubmissionChecklist()}

function parseFestivalText(txt,url=''){
 let f={url, status:'a_inscrire', iranExil:false}; let t=txt.replace(/\r/g,'');
 const grab=(rx)=>{let m=t.match(rx);return m?m[1].trim():''};
 f.deadline=toISO(grab(/Date limite d['’]inscription(?: des films)?\s*:?\s*\n+\s*(?:~~)?([^\n~]+)/i)||grab(/(?:Final|Standard|Regular|Late)\s+Deadline\s*\n+\s*([^\n]+)/i));
 f.price=grab(/Frais d['’]inscription\s*:?\s*\n+\s*(?:###\s*)?([^\n]+)/i)||'Prix à vérifier';
 f.duration=grab(/Durée maximum[^:]*:\s*([^\n]+)/i)||'À vérifier';
 f.minDuration=grab(/Durée minimum\s*:?\s*([^\n]+)/i);
 f.producedAfter=grab(/Films produits après[^:]*:\s*([^\n]+)/i);
 f.eligibleCountries=grab(/Pays de production\s*:\s*([^\n]+)/i);
 f.projectionFormat=grab(/Format de projection\s*:\s*([^\n]+)/i);
 f.subtitleRequirement=grab(/Sous-?titr(?:age|ages|es)\s*:?\s*([^\n]+)/i);
 f.response=toISO(grab(/Annonce des résultats\s*\n+\s*([^\n]+)/i));
 let title=grab(/(?:DOCFILMDEPOT\s*-\s*)?([^\n]{3,80})\n/i); if(title&&!/Festival entry management/i.test(title))f.name=title;
 f.eligibility=(t.match(/(?:CONDITIONS|CRITÈRES LIBRES)\s*:([\s\S]{0,1600})/i)||[])[1]?.trim()||'';
 return f
}
function toISO(s){if(!s)return '';let x=s.replace(/~~/g,'').trim().toLowerCase().replace('1er','1');let months={janvier:1,février:2,fevrier:2,mars:3,avril:4,mai:5,juin:6,juillet:7,août:8,aout:8,septembre:9,octobre:10,novembre:11,décembre:12,decembre:12};let m=x.match(/(\d{1,2})\s+([a-zéûôîà]+)\s+(\d{4})/);if(m&&months[m[2]])return `${m[3]}-${String(months[m[2]]).padStart(2,'0')}-${m[1].padStart(2,'0')}`;m=x.match(/(\d{1,2})[\/.-](\d{1,2})[\/.-](\d{4})/);if(m)return `${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;return ''}
openImport=function(kind){
 let isFilm=kind==='film';
 openModal(isFilm?'Importer la fiche du film':'Importer un festival',isFilm?`<div class=importbox><p>L'import direct du profil privé FilmFreeway n'est pas accessible depuis cette V5 locale. Tu peux néanmoins conserver son URL ici et remplir la fiche maître une seule fois.</p><div class=field><label>URL FilmFreeway</label><input name=importUrl type=url required></div><button class=primary>Enregistrer le lien</button></div>`:`<div class=importbox><p><b>Import FilmFreeway / Docfilmdepot</b></p><p>1. Colle l'URL. 2. Copie le texte de la page du festival dans la grande zone ci-dessous. La V5 extrait automatiquement les champs qu'elle reconnaît, puis ouvre la fiche pour vérification.</p><div class=field><label>URL du festival</label><input name=importUrl type=url placeholder="https://..."></div><div class=field><label>Contenu de la fiche</label><textarea name=pageText class=bigtext placeholder="Sélectionne le contenu de la page FilmFreeway ou Docfilmdepot, copie, puis colle ici…"></textarea></div><button class=primary>Analyser et préremplir</button></div>`);
 $('#editForm').onsubmit=e=>{e.preventDefault();let fd=new FormData(e.target),url=fd.get('importUrl')||'';if(isFilm){let film=JSON.parse(localStorage.getItem(FILM_KEY)||'{}');film.sourceUrl=url;localStorage.setItem(FILM_KEY,JSON.stringify(film));window.cloudSync?.scheduleIran();closeModal();loadFilm();return}let parsed=parseFestivalText(fd.get('pageText')||'',url);closeModal();editFestival();setTimeout(()=>{Object.entries(parsed).forEach(([k,v])=>{let el=$('#editForm [name="'+k+'"]');if(el&&v!==undefined)el.value=typeof v==='boolean'?String(v):v})},0)}
}

// V6 explicit bindings after corrected HTML
document.addEventListener('DOMContentLoaded',()=>{
 const imp=$('#importFestivalBtn'); if(imp) imp.onclick=()=>openImport('festival');
 const fi=$('#filmImportBtn'); if(fi) fi.onclick=()=>openImport('film');
 const sf=$('#saveFilmBtn'); if(sf) sf.onclick=saveFilm;
 const ff=$('#filmForm'); if(ff){ff.addEventListener('input',()=>{updateFilmProgress();renderSubmissionChecklist()});loadFilm();renderSubmissionChecklist();}
});

// ---- V7 Mission Locale (private local preview) ----
const ML_KEY='mission_locale_v7';
let ml=JSON.parse(localStorage.getItem(ML_KEY)||'null')||{dossier:{url:'',updated:''},residences:[],tasks:[],events:[]};
let mlDate=new Date(); mlDate.setDate(1);
function saveMl(){localStorage.setItem(ML_KEY,JSON.stringify(ml));window.cloudSync?.scheduleMission();renderMl()}
function mlFmt(s){if(!s)return '—';return new Date(s+'T12:00:00').toLocaleDateString('fr-FR',{day:'numeric',month:'short',year:'numeric'})}
function resStatusLabel(s){return ({a_etudier:'À étudier',a_preparer:'À préparer',depose:'Déposé',accepte:'Accepté',refuse:'Refusé'})[s]||'À étudier'}
function renderMl(){
 let now=new Date().toISOString().slice(0,10);
 let upcoming=ml.residences.filter(x=>x.deadline>=now).sort((a,b)=>a.deadline.localeCompare(b.deadline));
 $('#mlNextDeadline').textContent=upcoming[0]?mlFmt(upcoming[0].deadline):'—';$('#mlNextDeadlineName').textContent=upcoming[0]?.name||'Aucune aide renseignée';
 $('#mlOpenTasks').textContent=ml.tasks.filter(x=>!x.done).length;
 let terrain=ml.events.filter(x=>x.type==='shoot'&&x.date>=now).sort((a,b)=>a.date.localeCompare(b.date))[0];
 $('#mlNextShoot').textContent=terrain?mlFmt(terrain.date):'—';$('#mlNextShootName').textContent=terrain?.title||'Repérage / tournage';
 $('#mlUpcoming').innerHTML=[...upcoming.slice(0,3).map(x=>({date:x.deadline,title:x.name,type:'Deadline'})),...ml.events.filter(x=>x.date>=now).slice(0,3).map(x=>({date:x.date,title:x.title,type:x.type==='shoot'?'Terrain':'Deadline'}))].sort((a,b)=>a.date.localeCompare(b.date)).slice(0,5).map(x=>`<div class=uprow><b>${mlFmt(x.date)}</b><span>${esc(x.title)}</span><em>${x.type}</em></div>`).join('')||'<div class=empty>Rien à venir pour le moment.</div>';
 let dl=$('#dossierLinkDisplay'); if(ml.dossier.url){dl.textContent=ml.dossier.label||'Ouvrir le dernier dossier ↗';dl.href=ml.dossier.url;dl.target='_blank'}else{dl.textContent='Aucun lien renseigné';dl.removeAttribute('href')} $('#dossierUpdated').textContent=ml.dossier.updated?'Dernière mise à jour : '+mlFmt(ml.dossier.updated):'';
 renderResidences();renderTasks();renderMlCalendar()
}
function editDossier(){openModal('Dernier dossier',`<div class=formgrid><div class="field wide"><label>Nom / version</label><input name=label value="${esc(ml.dossier.label||'Dernier dossier')}"></div><div class="field wide"><label>Lien</label><input name=url type=url required value="${esc(ml.dossier.url||'')}" placeholder="https://…"></div><div class=field><label>Dernière mise à jour</label><input name=updated type=date value="${ml.dossier.updated||''}"></div></div><button class=primary>Enregistrer</button>`);$('#editForm').onsubmit=e=>{e.preventDefault();ml.dossier=Object.fromEntries(new FormData(e.target));saveMl();closeModal()}}
function editResidence(id){let r=ml.residences.find(x=>x.id===id)||{};openModal(id?'Modifier la résidence / aide':'Ajouter une résidence / aide',`<div class=formgrid><div class="field wide"><label>Nom</label><input name=name required value="${esc(r.name||'')}"></div><div class=field><label>Organisme</label><input name=org value="${esc(r.org||'')}"></div><div class=field><label>Lieu</label><input name=place value="${esc(r.place||'')}"></div><div class=field><label>Deadline</label><input type=date name=deadline required value="${r.deadline||''}"></div><div class=field><label>Dates de résidence</label><input name=residenceDates value="${esc(r.residenceDates||'')}"></div><div class=field><label>Montant / prise en charge</label><input name=amount value="${esc(r.amount||'')}"></div><div class=field><label>Statut</label><select name=status>${[['a_etudier','À étudier'],['a_preparer','À préparer'],['depose','Déposé'],['accepte','Accepté'],['refuse','Refusé']].map(x=>`<option value=${x[0]} ${r.status===x[0]?'selected':''}>${x[1]}</option>`).join('')}</select></div><div class="field wide"><label>Lien</label><input type=url name=url value="${esc(r.url||'')}"></div><div class="field wide"><label>Éligibilité / conditions</label><textarea name=eligibility>${esc(r.eligibility||'')}</textarea></div><div class="field wide"><label>Notes</label><textarea name=notes>${esc(r.notes||'')}</textarea></div></div><button class=primary>Enregistrer</button>`);$('#editForm').onsubmit=e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));o.id=id||'res-'+Date.now();if(id)Object.assign(r,o);else ml.residences.push(o);saveMl();closeModal()}}
function renderResidences(){let box=$('#residenceCards');if(!box)return;let q=($('#resSearch')?.value||'').toLowerCase(),st=$('#resStatus')?.value||'all';let a=ml.residences.filter(r=>(st==='all'||r.status===st)&&JSON.stringify(r).toLowerCase().includes(q)).sort((a,b)=>(a.deadline||'9999').localeCompare(b.deadline||'9999'));box.innerHTML=a.map(r=>`<article class=festival><div class=festtop><span class="status ${r.status}">${resStatusLabel(r.status)}</span><span class=datepill>${mlFmt(r.deadline)}</span></div><h3>${esc(r.name)}</h3><div class=meta>${esc(r.org||'')}${r.place?' · '+esc(r.place):''}</div>${r.eligibility?`<p>${esc(r.eligibility)}</p>`:''}<div class=actions>${r.url?`<a href="${esc(r.url)}" target=_blank>Voir ↗</a>`:''}<button onclick="editResidence('${r.id}')">Modifier</button><button class=danger onclick="ml.residences=ml.residences.filter(x=>x.id!=='${r.id}');saveMl()">Supprimer</button></div></article>`).join('')||'<div class=empty>Ajoute ici tes résidences et aides documentaires.</div>'}
function editTask(id){let t=ml.tasks.find(x=>x.id===id)||{};openModal(id?'Modifier la tâche':'Ajouter une tâche',`<div class=formgrid><div class="field wide"><label>Tâche</label><input name=title required value="${esc(t.title||'')}"></div><div class=field><label>Liste</label><select name=category><option value=writing ${t.category==='writing'?'selected':''}>Écriture</option><option value=shoot ${t.category==='shoot'?'selected':''}>Tournage / production</option></select></div><div class=field><label>Échéance (facultatif)</label><input type=date name=due value="${t.due||''}"></div><div class=field><label>Priorité</label><select name=priority><option>Normale</option><option ${t.priority==='Haute'?'selected':''}>Haute</option></select></div><div class="field wide"><label>Notes</label><textarea name=notes>${esc(t.notes||'')}</textarea></div></div><button class=primary>Enregistrer</button>`);$('#editForm').onsubmit=e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));o.id=id||'task-'+Date.now();o.done=t.done||false;if(id)Object.assign(t,o);else ml.tasks.push(o);saveMl();closeModal()}}
function renderTasks(){for(let cat of ['writing','shoot']){let box=$('#'+(cat==='writing'?'writingTasks':'shootTasks'));if(!box)continue;let a=ml.tasks.filter(x=>x.category===cat);box.innerHTML=a.map(t=>`<div class="taskitem ${t.done?'done':''}"><input type=checkbox ${t.done?'checked':''} onchange="let t=ml.tasks.find(x=>x.id==='${t.id}');t.done=this.checked;saveMl()"><div onclick="editTask('${t.id}')"><b>${esc(t.title)}</b>${t.due?`<small>${mlFmt(t.due)}</small>`:''}${t.priority==='Haute'?'<em>Priorité haute</em>':''}</div><button onclick="ml.tasks=ml.tasks.filter(x=>x.id!=='${t.id}');saveMl()">×</button></div>`).join('')||'<div class=taskempty>Aucune tâche</div>';let c=$('#'+(cat==='writing'?'writingCount':'shootCount'));if(c)c.textContent=a.filter(x=>!x.done).length+' à faire'}}
function editMlEvent(id,datePreset){let ev=ml.events.find(x=>x.id===id)||{date:datePreset||'',type:'shoot'};openModal(id?'Modifier l’événement':'Ajouter au calendrier',`<div class=formgrid><div class="field wide"><label>Événement</label><input name=title required value="${esc(ev.title||'')}"></div><div class=field><label>Date</label><input type=date name=date required value="${ev.date||''}"></div><div class=field><label>Type / couleur</label><select name=type><option value=deadline ${ev.type==='deadline'?'selected':''}>Deadline aide / résidence</option><option value=shoot ${ev.type==='shoot'?'selected':''}>Repérage / tournage</option></select></div><div class="field wide"><label>Notes</label><textarea name=notes>${esc(ev.notes||'')}</textarea></div></div><button class=primary>Enregistrer</button>`);$('#editForm').onsubmit=e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));o.id=id||'event-'+Date.now();if(id)Object.assign(ev,o);else ml.events.push(o);saveMl();closeModal()}}
function renderMlCalendar(){let box=$('#mlCalendar');if(!box)return;let y=mlDate.getFullYear(),m=mlDate.getMonth();$('#mlMonthTitle').textContent=mlDate.toLocaleDateString('fr-FR',{month:'long',year:'numeric'});let first=new Date(y,m,1),offset=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate();let cells=['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'].map(x=>`<div class=weekday>${x}</div>`);for(let i=0;i<offset;i++)cells.push('<div class="day mutedday"></div>');for(let d=1;d<=days;d++){let ds=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;let evs=[...ml.residences.filter(x=>x.deadline===ds).map(x=>({id:'',title:x.name,type:'deadline',res:true})),...ml.events.filter(x=>x.date===ds)];cells.push(`<div class=day ondblclick="editMlEvent(null,'${ds}')"><b>${d}</b>${evs.map(e=>`<div class="mlevent ${e.type}" ${e.id?`onclick="event.stopPropagation();editMlEvent('${e.id}')"`:''}>${esc(e.title)}</div>`).join('')}</div>`)}box.innerHTML=cells.join('')}
document.addEventListener('DOMContentLoaded',()=>{
 document.querySelectorAll('.missionnav').forEach(b=>b.onclick=()=>page(b.dataset.page));
 $('#editDossierBtn')?.addEventListener('click',editDossier);$('#lastDossierBtn')?.addEventListener('click',()=>ml.dossier.url?window.open(ml.dossier.url,'_blank'):editDossier());
 $('#addResidenceBtn')?.addEventListener('click',()=>editResidence());$('#resSearch')?.addEventListener('input',renderResidences);$('#resStatus')?.addEventListener('change',renderResidences);
 $('#addTaskBtn')?.addEventListener('click',()=>editTask());$('#addMlEventBtn')?.addEventListener('click',()=>editMlEvent());
 $('#mlPrev')?.addEventListener('click',()=>{mlDate.setMonth(mlDate.getMonth()-1);renderMlCalendar()});$('#mlNext')?.addEventListener('click',()=>{mlDate.setMonth(mlDate.getMonth()+1);renderMlCalendar()});$('#mlToday')?.addEventListener('click',()=>{mlDate=new Date();mlDate.setDate(1);renderMlCalendar()});
 renderMl();
});

// ---- V8: Résidences / Aides séparées + base documentaire vérifiée ----
if(!ml.v8Seeded){
 ml.residences = (ml.residences||[]).map(x=>({...x,kind:x.kind||'residence'}));
 const seed=[
 {id:'seed-tyfilms-2027',kind:'residence',name:'Ty Films — Résidences d’écriture documentaire 2027',org:'Ty Films',place:'Mellionnec (Côtes-d’Armor)',deadline:'2026-11-15',residenceDates:'4 semaines en 2027 · 1re session 8–12 mars 2027',status:'a_etudier',url:'https://www.tyfilms.fr/Residences-d-ecriture-2027.html',eligibility:'Tous types de documentaires de création. Durée, forme et état d’avancement non éliminatoires. Un projet déjà soumis n’est retenu qu’en cas d’évolution importante.',amount:'Accompagnement + hébergement + repas pris en charge ; déplacements à la charge de l’auteur·ice.',notes:'Dossier : lettre de motivation/besoins (2 p. max), résumé + note d’intention + traitement (15 p. max au total), CV, liens vidéo possibles (15 min max). Envoi papier + PDF. Résultats annoncés le 5 février 2027.',verified:'2026-10-01'},
 {id:'seed-peripherie-47',kind:'residence',name:'Périphérie — Cinéastes en résidence, 47e commission',org:'Périphérie',place:'Montreuil / Seine-Saint-Denis',deadline:'2026-10-15',residenceDates:'Appel ouvert du 1er au 15 octobre 2026',status:'a_etudier',url:'https://www.peripherie.asso.fr/cineastes-en-residence/soumettre-un-projet/',eligibility:'Documentaire de création de plus de 30 min, en fin de tournage ou entièrement tourné. Production basée en France, ou sans production si réalisateur·ice basé·e en France.',amount:'Accompagnement de postproduction / montage — vérifier les modalités de la commission.',notes:'Attention : ce n’est pas une résidence d’écriture de projet en amont ; utile surtout si Mission Locale est déjà tourné ou en fin de tournage.',verified:'2026-10-01'},
 {id:'seed-fidab-2027',kind:'residence',name:'FIDAB 2027 — Résidence d’écriture documentaire',org:'Festival International du Documentaire Africain de Bamako',place:'Bamako, Mali',deadline:'2026-10-15',residenceDates:'8–14 janvier 2027',status:'a_etudier',url:'https://www.fidab.org/',eligibility:'Auteur·ice/réalisateur·ice africain·e ou de la diaspora, 18 ans minimum, ayant déjà réalisé au moins un court ou moyen métrage ; projet documentaire en développement.',amount:'Voyage, hébergement et restauration annoncés comme pris en charge.',notes:'6 projets sélectionnés ; accompagnement intensif et pitching. À vérifier selon l’éligibilité personnelle du projet.',verified:'2026-10-01'},
 {id:'seed-scam-bdr',kind:'aide',name:'Brouillon d’un rêve documentaire',org:'La Scam',place:'France / dépôt en ligne',deadline:'2026-11-12',residenceDates:'Session de dépôt en ligne',status:'a_etudier',url:'https://www.lascam.fr/lessentiel/bourses-brouillon-dun-reve/brouillon-dun-reve-documentaire/',eligibility:'Documentaire de création ou essai, forme unitaire, moyen ou long métrage. Film de plus de 40 min. L’aide vise le début de conception/écriture, pas la production ou postproduction.',amount:'Bourse d’écriture — montant à vérifier sur l’appel en cours.',notes:'La page officielle affiche la prochaine session le 12 novembre 2026. Compte LaScam requis pour déposer.',verified:'2026-10-01'}
 ];
 const ids=new Set(ml.residences.map(x=>x.id)); seed.forEach(x=>{if(!ids.has(x.id))ml.residences.push(x)});
 ml.v8Seeded=true;localStorage.setItem(ML_KEY,JSON.stringify(ml));
}
let resKind='residence';
function setResKind(k){resKind=k;$('#tabResidences')?.classList.toggle('active',k==='residence');$('#tabAides')?.classList.toggle('active',k==='aide');let b=$('#addResidenceBtn');if(b)b.textContent=k==='residence'?'+ Ajouter une résidence':'+ Ajouter une aide';renderResidences()}
renderResidences=function(){let box=$('#residenceCards');if(!box)return;let q=($('#resSearch')?.value||'').toLowerCase(),st=$('#resStatus')?.value||'all';let a=ml.residences.filter(r=>(r.kind||'residence')===resKind&&(st==='all'||r.status===st)&&JSON.stringify(r).toLowerCase().includes(q)).sort((a,b)=>(a.deadline||'9999').localeCompare(b.deadline||'9999'));box.innerHTML=a.map(r=>`<article class=festival><div class=festtop><span class="status ${r.status}">${resStatusLabel(r.status)}</span><span class=datepill>${mlFmt(r.deadline)}</span></div><div class="kindlabel ${r.kind||'residence'}">${(r.kind||'residence')==='residence'?'RÉSIDENCE':'AIDE / BOURSE'}</div><h3>${esc(r.name)}</h3><div class=meta>${esc(r.org||'')}${r.place?' · '+esc(r.place):''}</div>${r.residenceDates?`<p><b>${(r.kind||'residence')==='residence'?'Dates':'Dépôt'} :</b> ${esc(r.residenceDates)}</p>`:''}${r.amount?`<p><b>${(r.kind||'residence')==='residence'?'Prise en charge':'Montant'} :</b> ${esc(r.amount)}</p>`:''}${r.eligibility?`<p><b>Éligibilité :</b> ${esc(r.eligibility)}</p>`:''}${r.notes?`<details><summary>Infos / dossier demandé</summary><p>${esc(r.notes)}</p></details>`:''}${r.verified?`<small class=verified>Vérifié le ${mlFmt(r.verified)}</small>`:''}<div class=actions>${r.url?`<a href="${esc(r.url)}" target=_blank>Site officiel ↗</a>`:''}<button onclick="editResidence('${r.id}')">Modifier</button><button class=danger onclick="ml.residences=ml.residences.filter(x=>x.id!=='${r.id}');saveMl()">Supprimer</button></div></article>`).join('')||`<div class=empty>Aucune ${resKind==='residence'?'résidence':'aide'} pour le moment.</div>`}
editResidence=function(id){let r=ml.residences.find(x=>x.id===id)||{kind:resKind};let isA=(r.kind||resKind)==='aide';openModal(id?'Modifier':'Ajouter '+(isA?'une aide / bourse':'une résidence'),`<div class=formgrid><div class=field><label>Type</label><select name=kind><option value=residence ${!isA?'selected':''}>Résidence</option><option value=aide ${isA?'selected':''}>Aide / bourse</option></select></div><div class="field wide"><label>Nom</label><input name=name required value="${esc(r.name||'')}"></div><div class=field><label>Organisme</label><input name=org value="${esc(r.org||'')}"></div><div class=field><label>Lieu</label><input name=place value="${esc(r.place||'')}"></div><div class=field><label>Deadline de candidature</label><input type=date name=deadline required value="${r.deadline||''}"></div><div class=field><label>${isA?'Session / période de dépôt':'Dates de résidence'}</label><input name=residenceDates value="${esc(r.residenceDates||'')}"></div><div class="field wide"><label>${isA?'Montant / nature de l’aide':'Prise en charge (hébergement, repas, voyage…)'}</label><input name=amount value="${esc(r.amount||'')}"></div><div class=field><label>Statut</label><select name=status>${[['a_etudier','À étudier'],['a_preparer','À préparer'],['depose','Déposé'],['accepte','Accepté'],['refuse','Refusé']].map(x=>`<option value=${x[0]} ${r.status===x[0]?'selected':''}>${x[1]}</option>`).join('')}</select></div><div class="field wide"><label>Site / appel officiel</label><input type=url name=url value="${esc(r.url||'')}"></div><div class="field wide"><label>Éligibilité / conditions</label><textarea name=eligibility>${esc(r.eligibility||'')}</textarea></div><div class="field wide"><label>Pièces demandées / infos utiles</label><textarea name=notes>${esc(r.notes||'')}</textarea></div></div><button class=primary>Enregistrer</button>`);$('#editForm').onsubmit=e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));o.id=id||'res-'+Date.now();o.verified=r.verified||'';if(id)Object.assign(r,o);else ml.residences.push(o);saveMl();closeModal();setResKind(o.kind)}}
document.addEventListener('DOMContentLoaded',()=>{$('#tabResidences')?.addEventListener('click',()=>setResKind('residence'));$('#tabAides')?.addEventListener('click',()=>setResKind('aide'));$('#addResidenceBtn').onclick=()=>editResidence();setResKind('residence')});

// ---- V9 Project switcher + Google-like Mission Locale calendar ----
function setProject(project){
 const mission=project==='mission';
 document.body.classList.toggle('project-mission',mission);
 document.body.classList.toggle('project-iran',!mission);
 $('#switchIran')?.classList.toggle('active',!mission);
 $('#switchMission')?.classList.toggle('active',mission);
 localStorage.setItem('active_project_v9',project);
 if(mission) page('mission-home'); else page('dashboard');
}
function quickMlEvent(datePreset){
 const date=datePreset||new Date().toISOString().slice(0,10);
 openModal('Nouvel événement',`<div class="quickevent">
 <input class="eventtitle" name=title placeholder="Ajouter un titre" autofocus required>
 <div class=quickrow><span>📅</span><input type=date name=date value="${date}" required><input type=time name=time></div>
 <div class=quickrow><span>●</span><select name=type><option value=residence>Résidence</option><option value=aid>Aide / bourse</option><option value=shoot selected>Repérage / tournage</option></select></div>
 <div class=quickrow><span>📍</span><input name=place placeholder="Ajouter un lieu"></div>
 <div class=quickrow><span>≡</span><textarea name=notes placeholder="Ajouter une description ou des notes"></textarea></div>
 </div><div class=modalactions><button type=button class=secondary onclick=closeModal()>Annuler</button><button class=primary>Enregistrer</button></div>`);
 $('#editForm').onsubmit=e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));o.id='event-'+Date.now();ml.events.push(o);saveMl();closeModal()}
}
editMlEvent=function(id,datePreset){
 if(!id){quickMlEvent(datePreset);return}
 let ev=ml.events.find(x=>x.id===id)||{};
 openModal('Modifier l’événement',`<div class="quickevent">
 <input class=eventtitle name=title required value="${esc(ev.title||'')}">
 <div class=quickrow><span>📅</span><input type=date name=date required value="${ev.date||''}"><input type=time name=time value="${ev.time||''}"></div>
 <div class=quickrow><span>●</span><select name=type><option value=residence ${ev.type==='residence'?'selected':''}>Résidence</option><option value=aid ${ev.type==='aid'?'selected':''}>Aide / bourse</option><option value=shoot ${ev.type==='shoot'?'selected':''}>Repérage / tournage</option></select></div>
 <div class=quickrow><span>📍</span><input name=place value="${esc(ev.place||'')}" placeholder="Ajouter un lieu"></div>
 <div class=quickrow><span>≡</span><textarea name=notes placeholder="Description">${esc(ev.notes||'')}</textarea></div>
 </div><div class=modalactions><button type=button class=danger onclick="ml.events=ml.events.filter(x=>x.id!=='${id}');saveMl();closeModal()">Supprimer</button><button class=primary>Enregistrer</button></div>`);
 $('#editForm').onsubmit=e=>{e.preventDefault();Object.assign(ev,Object.fromEntries(new FormData(e.target)));saveMl();closeModal()}
}
renderMlCalendar=function(){
 let box=$('#mlCalendar');if(!box)return;let y=mlDate.getFullYear(),m=mlDate.getMonth();
 $('#mlMonthTitle').textContent=mlDate.toLocaleDateString('fr-FR',{month:'long',year:'numeric'});
 let first=new Date(y,m,1),offset=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate();
 let cells=['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'].map(x=>`<div class=weekday>${x}</div>`);
 for(let i=0;i<offset;i++)cells.push('<div class="day mutedday"></div>');
 for(let d=1;d<=days;d++){
  let ds=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;
  let auto=ml.residences.filter(x=>x.deadline===ds).map(x=>({title:x.name,type:(x.kind==='aide'?'aid':'residence'),auto:true,id:x.id}));
  let evs=[...auto,...ml.events.filter(x=>x.date===ds)];
  cells.push(`<div class=day onclick="if(event.target===this||event.target.tagName==='B')quickMlEvent('${ds}')"><b>${d}</b>${evs.map(e=>`<div class="mlevent ${e.type}" ${e.auto?`title="Créé automatiquement depuis ${e.type==='aid'?'Aides':'Résidences'}"`:`onclick="event.stopPropagation();editMlEvent('${e.id}')"`}>${e.time?`<small>${e.time}</small> `:''}${esc(e.title)}</div>`).join('')}</div>`)
 }
 box.innerHTML=cells.join('')
}
document.addEventListener('DOMContentLoaded',()=>{
 $('#switchIran')?.addEventListener('click',()=>setProject('iran'));
 $('#switchMission')?.addEventListener('click',()=>setProject('mission'));
 let active=localStorage.getItem('active_project_v9')||'iran';
 document.body.classList.toggle('project-mission',active==='mission');document.body.classList.toggle('project-iran',active!=='mission');
 $('#switchIran')?.classList.toggle('active',active!=='mission');$('#switchMission')?.classList.toggle('active',active==='mission');
 $('#addMlEventBtn').onclick=()=>quickMlEvent();
 renderMlCalendar();
});

function switchProjectFixed(project){
 const mission=project==='mission';
 const i=document.getElementById('iranProjectNav'),m=document.getElementById('missionProjectNav');
 if(i)i.style.display=mission?'none':'block'; if(m)m.style.display=mission?'block':'none';
 document.getElementById('switchIranFixed')?.classList.toggle('active',!mission);
 document.getElementById('switchMissionFixed')?.classList.toggle('active',mission);
 document.querySelectorAll('.old-project-label').forEach(x=>x.style.display='none');
 localStorage.setItem('active_project_v9b',project);
 page(mission?'mission-home':'dashboard');
}
document.addEventListener('DOMContentLoaded',()=>{
 document.getElementById('switchIranFixed')?.addEventListener('click',()=>switchProjectFixed('iran'));
 document.getElementById('switchMissionFixed')?.addEventListener('click',()=>switchProjectFixed('mission'));
 const p=localStorage.getItem('active_project_v9b')||'iran';
 const mission=p==='mission',i=document.getElementById('iranProjectNav'),m=document.getElementById('missionProjectNav');
 if(i)i.style.display=mission?'none':'block'; if(m)m.style.display=mission?'block':'none';
 document.getElementById('switchIranFixed')?.classList.toggle('active',!mission);
 document.getElementById('switchMissionFixed')?.classList.toggle('active',mission);
 document.querySelectorAll('.old-project-label').forEach(x=>x.style.display='none');
});

// ---- V10: Mission Locale nav restored + current opportunities + date ranges ----
if(!ml.v10Seeded){
 const more=[
 {id:'v10-fipadoc-regional',kind:'residence',subtype:'Pitch / développement',name:'FIPADOC — Pitchs Premiers Films en Région 2027',org:'FIPADOC / ALCA',place:'Biarritz · Nouvelle-Aquitaine',deadline:'2026-11-02',residenceDates:'Session au FIPADOC 2027',status:'a_etudier',url:'https://www.fipadoc.com/fr/pitchs-premiers-films-en-region',eligibility:'Premier projet de long métrage documentaire ; dispositif destiné aux jeunes talents de Nouvelle-Aquitaine. Vérifier les critères complets de l’appel.',amount:'Accompagnement au pitch + prix de 1 500 € en écriture doté par la Région Nouvelle-Aquitaine.',notes:'Travail collectif et individuel, puis présentation devant producteurs et diffuseurs.',verified:'2026-10-01'},
 {id:'v10-parisdoc-wip',kind:'residence',subtype:'Work in Progress',name:'ParisDOC Works-in-Progress 2027 — Cinéma du Réel',org:'Cinéma du Réel / ParisDOC',place:'Paris',deadline:'2026-12-21',residenceDates:'Inscriptions : 2 novembre – 21 décembre 2026 · WIP : 24–25 mars 2027',status:'a_etudier',url:'https://www.cinemadureel.org/works-in-progress-2027-14e-edition-24-25-mars-2027/',eligibility:'Long métrage documentaire en cours, français ou international ; sélection selon étape de fabrication, besoins et potentiel de diffusion.',amount:'Mise en relation avec professionnels de la diffusion et de l’exploitation.',notes:'Ce n’est pas une résidence d’écriture : catégorie WIP / industrie.',verified:'2026-10-01'},
 {id:'v10-vdr',kind:'residence',subtype:'Pitch / WIP',name:'Visions du Réel Industry 2027 — projets',org:'Visions du Réel',place:'Nyon, Suisse',deadline:'2026-12-15',residenceDates:'Early deadline : 2 novembre 2026 · finale : 15 décembre 2026',status:'a_etudier',url:'https://www.visionsdureel.ch/en/call-for-entries/',eligibility:'Projets documentaires pour VdR–Pitching, VdR–Work in Progress ou VdR–Rough Cut Lab ; règlement spécifique selon activité.',amount:'Accès aux activités Industry selon sélection.',notes:'Pitch/WIP/Rough Cut, pas une résidence d’écriture au sens strict.',verified:'2026-10-01'},
 {id:'v10-fipadoc-int',kind:'residence',subtype:'Pitch international',name:'FIPADOC — Pitchs internationaux 2027',org:'FIPADOC',place:'Biarritz',deadline:'2026-10-02',residenceDates:'Pitchs : 27–28 janvier 2027',status:'a_etudier',url:'https://www.fipadoc.com/fr/pitchs-internationaux',eligibility:'Appel destiné aux sociétés de production ; consulter les critères détaillés de l’édition 2027.',amount:'Plusieurs prix et soutiens annoncés, dont coproduction, postproduction et accompagnement.',notes:'Présentation devant des décisionnaires, diffuseurs, vendeurs, fonds et festivals.',verified:'2026-10-01'},
 {id:'v10-idfa-project-space',kind:'residence',subtype:'Développement international',name:'IDFA Project Space 2027',org:'IDFA',place:'Amsterdam + en ligne',deadline:'',residenceDates:'Candidatures annoncées de décembre 2026 à février 2027 · date précise à venir',status:'a_etudier',url:'https://professionals.idfa.nl/training-funding/training/about-idfas-training-programs/',eligibility:'Réalisateur·ice de premier ou deuxième documentaire, accompagné·e d’un partenaire créatif (producteur·ice, coréalisateur·ice ou monteur·euse).',amount:'Programme de mentorat et développement de projet.',notes:'À surveiller : IDFA annonce l’ouverture en décembre 2026 et la clôture en février 2027 sans date précise à ce jour.',verified:'2026-10-01'},
 {id:'v10-varan',kind:'residence',subtype:'Formation',name:'Ateliers Varan — Pratique de la réalisation documentaire',org:'Ateliers Varan',place:'Paris',deadline:'',residenceDates:'Session : 12 octobre – 1er décembre 2026',status:'a_etudier',url:'https://www.ateliersvaran.com/',eligibility:'Formation documentaire ; ce n’est pas une résidence d’écriture. Candidatures/financements selon modalités Varan et Afdas.',amount:'Formation — financement possible selon situation.',notes:'Conservé depuis ta liste mais classé Formation pour ne pas le confondre avec une résidence.',verified:'2026-10-01'}
 ];
 const ids=new Set(ml.residences.map(x=>x.id)); more.forEach(x=>{if(!ids.has(x.id))ml.residences.push(x)});
 ml.v10Seeded=true;localStorage.setItem(ML_KEY,JSON.stringify(ml));
}
function switchProjectV10(project){
 const mission=project==='mission';
 const iran=document.getElementById('iranProjectNav'), old=document.getElementById('missionProjectNav'), mn=document.getElementById('missionProjectNavV10');
 if(iran)iran.style.display=mission?'none':'block'; if(old)old.style.display='none'; if(mn)mn.style.display=mission?'block':'none';
 document.getElementById('switchIranFixed')?.classList.toggle('active',!mission);
 document.getElementById('switchMissionFixed')?.classList.toggle('active',mission);
 localStorage.setItem('active_project_v10',project); page(mission?'mission-home':'dashboard');
}
function quickMlEventV10(datePreset){
 const d=datePreset||new Date().toISOString().slice(0,10);
 openModal('Nouvel événement',`<div class="quickevent">
 <input class="eventtitle" name=title placeholder="Ajouter un titre" autofocus required>
 <div class=quickrow><span>📅</span><div class=rangefields><label>Début<input type=date name=startDate value="${d}" required></label><label>Heure<input type=time name=startTime></label></div></div>
 <div class=quickrow><span>→</span><div class=rangefields><label>Fin<input type=date name=endDate value="${d}" required></label><label>Heure<input type=time name=endTime></label></div></div>
 <div class=quickrow><span>●</span><select name=type><option value=residence>Résidence</option><option value=aid>Aide / bourse</option><option value=shoot selected>Repérage / tournage</option></select></div>
 <div class=quickrow><span>📍</span><input name=place placeholder="Ajouter un lieu"></div>
 <div class=quickrow><span>≡</span><textarea name=notes placeholder="Ajouter une description ou des notes"></textarea></div>
 </div><div class=modalactions><button type=button class=secondary onclick=closeModal()>Annuler</button><button class=primary>Enregistrer</button></div>`);
 $('#editForm').onsubmit=e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));if(o.endDate<o.startDate){alert('La date de fin doit être après la date de début.');return}o.id='event-'+Date.now();o.date=o.startDate;o.time=o.startTime;ml.events.push(o);saveMl();closeModal()}
}
function dateInRange(ds,a,b){return ds>=a&&ds<=(b||a)}
renderMlCalendar=function(){
 let box=$('#mlCalendar');if(!box)return;let y=mlDate.getFullYear(),m=mlDate.getMonth();
 $('#mlMonthTitle').textContent=mlDate.toLocaleDateString('fr-FR',{month:'long',year:'numeric'});
 let first=new Date(y,m,1),offset=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate(),cells=['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'].map(x=>`<div class=weekday>${x}</div>`);
 for(let i=0;i<offset;i++)cells.push('<div class="day mutedday"></div>');
 for(let d=1;d<=days;d++){let ds=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;
  let auto=ml.residences.filter(x=>x.deadline===ds).map(x=>({title:x.name,type:x.kind==='aide'?'aid':'residence',auto:true,id:x.id}));
  let manual=ml.events.filter(x=>dateInRange(ds,x.startDate||x.date,x.endDate||x.date));
  let evs=[...auto,...manual];
  cells.push(`<div class=day onclick="if(event.target===this||event.target.tagName==='B')quickMlEventV10('${ds}')"><b>${d}</b>${evs.map(e=>`<div class="mlevent ${e.type}" ${e.auto?'':`onclick="event.stopPropagation();editMlEventV10('${e.id}')"`}>${esc(e.title)}</div>`).join('')}</div>`)
 } box.innerHTML=cells.join('')
}
function editMlEventV10(id){
 let ev=ml.events.find(x=>x.id===id);if(!ev)return;
 let sd=ev.startDate||ev.date,ed=ev.endDate||ev.date;
 openModal('Modifier l’événement',`<div class="quickevent"><input class=eventtitle name=title required value="${esc(ev.title||'')}">
 <div class=quickrow><span>📅</span><div class=rangefields><label>Début<input type=date name=startDate value="${sd}" required></label><label>Heure<input type=time name=startTime value="${ev.startTime||ev.time||''}"></label></div></div>
 <div class=quickrow><span>→</span><div class=rangefields><label>Fin<input type=date name=endDate value="${ed}" required></label><label>Heure<input type=time name=endTime value="${ev.endTime||''}"></label></div></div>
 <div class=quickrow><span>●</span><select name=type><option value=residence ${ev.type==='residence'?'selected':''}>Résidence</option><option value=aid ${ev.type==='aid'?'selected':''}>Aide / bourse</option><option value=shoot ${ev.type==='shoot'?'selected':''}>Repérage / tournage</option></select></div>
 <div class=quickrow><span>📍</span><input name=place value="${esc(ev.place||'')}"></div><div class=quickrow><span>≡</span><textarea name=notes>${esc(ev.notes||'')}</textarea></div></div>
 <div class=modalactions><button type=button class=danger onclick="ml.events=ml.events.filter(x=>x.id!=='${id}');saveMl();closeModal()">Supprimer</button><button class=primary>Enregistrer</button></div>`);
 $('#editForm').onsubmit=e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));if(o.endDate<o.startDate){alert('La date de fin doit être après la date de début.');return}Object.assign(ev,o,{date:o.startDate,time:o.startTime});saveMl();closeModal()}
}
document.addEventListener('DOMContentLoaded',()=>{
 document.querySelectorAll('.missionnavv10').forEach(b=>b.addEventListener('click',()=>page(b.dataset.page)));
 document.getElementById('switchIranFixed').onclick=()=>switchProjectV10('iran');document.getElementById('switchMissionFixed').onclick=()=>switchProjectV10('mission');
 const p=localStorage.getItem('active_project_v10')||'iran',mission=p==='mission';
 const iran=document.getElementById('iranProjectNav'),old=document.getElementById('missionProjectNav'),mn=document.getElementById('missionProjectNavV10');
 if(iran)iran.style.display=mission?'none':'block';if(old)old.style.display='none';if(mn)mn.style.display=mission?'block':'none';
 document.getElementById('switchIranFixed')?.classList.toggle('active',!mission);document.getElementById('switchMissionFixed')?.classList.toggle('active',mission);
 document.getElementById('addMlEventBtn').onclick=()=>quickMlEventV10(); renderMl();
});

// ---- V12 clean UX patch ----
let resTypeFilterV12='all';
function setResTypeFilterV12(v){resTypeFilterV12=v;['All','Aides','Residences'].forEach(k=>document.getElementById('filter'+k)?.classList.toggle('active',v===({All:'all',Aides:'aide',Residences:'residence'}[k])));renderResidencesV12()}
function renderResidencesV12(){let box=$('#residenceCards');if(!box)return;let q=($('#resSearch')?.value||'').toLowerCase(),st=$('#resStatus')?.value||'all';let a=ml.residences.filter(r=>{let k=r.kind||'residence';return(resTypeFilterV12==='all'||k===resTypeFilterV12)&&(st==='all'||r.status===st)&&JSON.stringify(r).toLowerCase().includes(q)}).sort((a,b)=>(a.deadline||'9999').localeCompare(b.deadline||'9999'));box.innerHTML=a.map(r=>`<article class="festival ${r.kind==='aide'?'aidcardv12':'rescardv12'}"><div class=festtop><span class="status ${r.status}">${resStatusLabel(r.status)}</span><span class=datepill>${mlFmt(r.deadline)}</span></div><div class="kindlabel ${r.kind||'residence'}">${r.kind==='aide'?'AIDE / BOURSE':'RÉSIDENCE'}</div><h3>${esc(r.name)}</h3><div class=meta>${esc(r.org||'')}${r.place?' · '+esc(r.place):''}</div>${r.residenceDates?`<p><b>Dates / période :</b> ${esc(r.residenceDates)}</p>`:''}${r.amount?`<p><b>Montant / prise en charge :</b> ${esc(r.amount)}</p>`:''}${r.eligibility?`<p><b>Éligibilité :</b> ${esc(r.eligibility)}</p>`:''}${r.notes?`<details><summary>Infos / dossier demandé</summary><p>${esc(r.notes)}</p></details>`:''}<div class=actions>${r.url?`<a href="${esc(r.url)}" target=_blank>Site officiel ↗</a>`:''}<button onclick="editResidenceV12('${r.id}')">Modifier</button><button class=danger onclick="ml.residences=ml.residences.filter(x=>x.id!=='${r.id}');ml.tasks=ml.tasks.filter(t=>t.linkedAidId!=='${r.id}');saveMl()">Supprimer</button></div></article>`).join('')||'<div class=empty>Aucun élément dans ce filtre.</div>'}
function syncAidTaskV12(aid,urgent){let t=ml.tasks.find(x=>x.linkedAidId===aid.id),d={id:t?.id||'task-aid-'+aid.id,title:'Préparer — '+aid.name,category:'writing',due:aid.deadline||'',priority:urgent?'Haute':'Normale',done:t?.done||false,linkedAidId:aid.id,notes:'Créée automatiquement depuis l’aide / bourse.'};t?Object.assign(t,d):ml.tasks.push(d)}
function editResidenceV12(id){let r=ml.residences.find(x=>x.id===id)||{kind:'residence'},isAid=(r.kind==='aide'),linked=ml.tasks.find(t=>t.linkedAidId===r.id);openModal(id?'Modifier':'Ajouter',`<div class=formgrid><div class=field><label>Type</label><select name=kind id=kindV12><option value=residence ${!isAid?'selected':''}>Résidence</option><option value=aide ${isAid?'selected':''}>Aide / bourse</option></select></div><div class="field wide"><label>Nom</label><input name=name required value="${esc(r.name||'')}"></div><div class=field><label>Organisme</label><input name=org value="${esc(r.org||'')}"></div><div class=field><label>Lieu</label><input name=place value="${esc(r.place||'')}"></div><div class=field><label>Deadline</label><input type=date name=deadline value="${r.deadline||''}"></div><div class=field><label>Dates / période</label><input name=residenceDates value="${esc(r.residenceDates||'')}"></div><div class="field wide"><label>Montant / prise en charge</label><input name=amount value="${esc(r.amount||'')}"></div><div class=field><label>Statut</label><select name=status>${[['a_etudier','À étudier'],['a_preparer','À préparer'],['depose','Déposé'],['accepte','Accepté'],['refuse','Refusé']].map(x=>`<option value=${x[0]} ${r.status===x[0]?'selected':''}>${x[1]}</option>`).join('')}</select></div><div class="field wide"><label>Site / appel officiel</label><input type=url name=url value="${esc(r.url||'')}"></div><div class="field wide"><label>Éligibilité</label><textarea name=eligibility>${esc(r.eligibility||'')}</textarea></div><div class="field wide"><label>Notes</label><textarea name=notes>${esc(r.notes||'')}</textarea></div><div id=aidUrgencyV12 class="field wide aidurgentv12" style="${isAid?'':'display:none'}"><b>Tâche d’écriture créée automatiquement</b><p>« Préparer — nom de l’aide » avec la même deadline.</p><label class=urgentcheckv12><input type=checkbox name=urgent ${linked?.priority==='Haute'?'checked':''}> 🔥 C’est urgent</label></div></div><button class=primary>Enregistrer</button>`);$('#kindV12').onchange=e=>$('#aidUrgencyV12').style.display=e.target.value==='aide'?'block':'none';$('#editForm').onsubmit=e=>{e.preventDefault();let fd=new FormData(e.target),urgent=fd.has('urgent'),o=Object.fromEntries(fd);delete o.urgent;o.id=id||'res-'+Date.now();o.verified=r.verified||'';if(id)Object.assign(r,o);else{r=o;ml.residences.push(r)}if(o.kind==='aide')syncAidTaskV12(r,urgent);else ml.tasks=ml.tasks.filter(t=>t.linkedAidId!==r.id);saveMl();closeModal();renderResidencesV12()}}
editResidence=editResidenceV12;renderResidences=renderResidencesV12;
// Agenda V12: day click creates range; event click opens detail/edit form.
function openMlEventV12(id){editMlEventV10(id)}
renderMlCalendar=function(){let box=$('#mlCalendar');if(!box)return;let y=mlDate.getFullYear(),m=mlDate.getMonth();$('#mlMonthTitle').textContent=mlDate.toLocaleDateString('fr-FR',{month:'long',year:'numeric'});let first=new Date(y,m,1),offset=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate(),cells=['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'].map(x=>`<div class=weekday>${x}</div>`);for(let i=0;i<offset;i++)cells.push('<div class="day mutedday"></div>');for(let d=1;d<=days;d++){let ds=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;let auto=ml.residences.filter(x=>x.deadline===ds).map(x=>({title:x.name,type:x.kind==='aide'?'aid':'residence',auto:true})),manual=ml.events.filter(x=>dateInRange(ds,x.startDate||x.date,x.endDate||x.date));cells.push(`<div class=day onclick="if(event.target===this||event.target.tagName==='B')quickMlEventV10('${ds}')"><b>${d}</b>${[...auto,...manual].map(e=>`<div class="mlevent ${e.type}" ${e.auto?'title="Deadline automatique — modifiable depuis Résidences & aides"':`onclick="event.stopPropagation();openMlEventV12('${e.id}')" title="Cliquer pour voir / modifier"`}>${esc(e.title)}</div>`).join('')}</div>`)}box.innerHTML=cells.join('')}
document.addEventListener('DOMContentLoaded',()=>{document.getElementById('filterAll')?.addEventListener('click',()=>setResTypeFilterV12('all'));document.getElementById('filterAides')?.addEventListener('click',()=>setResTypeFilterV12('aide'));document.getElementById('filterResidences')?.addEventListener('click',()=>setResTypeFilterV12('residence'));document.getElementById('addResidenceBtn').onclick=()=>editResidenceV12();document.getElementById('resSearch')?.addEventListener('input',renderResidencesV12);document.getElementById('resStatus')?.addEventListener('change',renderResidencesV12);setResTypeFilterV12('all')});
